### ISSUE TITLE
Crash when accessing https://privatesky.xyz/?API/opendsu-communication

### ISSUE THREAD

**Issue by alexgheorghiu** [PrivateSky/privatesky-xyz#5]
My Firefox(77.0.1 (64-bit)) under Linux Mint 20 (Ubuntu 20) crashes when trying to access https://privatesky.xyz/?API/opendsu-communication 

Here is the screenshot.
![privatesky-crash](https://user-images.githubusercontent.com/1814282/92593458-d418a080-f2a9-11ea-8e1b-d72d9a2ca9ec.png)

Attached is the video screen recording.

[privatesky-crash.mp4.zip](https://github.com/PrivateSky/privatesky-xyz/files/5194815/privatesky-crash.mp4.zip)

**Comment by denypatrascu** [comment]
Cardinal issue.

Now https://privatesky.xyz uses WebCardinal witch does not have "query-routes".
The problem was caused by case sensitivity after `?` in `window.location` and a bad configuration in `menu.json`.

**Comment by denypatrascu** [comment]
Current location of that page: https://privatesky.xyz/api/opendsu-communication
